services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: ''
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      # single quotes so  is taken literally by YAML
      test: ['CMD-SHELL', 'pg_isready -U ']
      interval: 5s
      retries: 10

  api:
    build: .
    environment:
      PGHOST: db
      PGUSER: ''
      PGPASSWORD: ''
      PGDATABASE: ''
      PGPORT: 5432
      PORT: ''
    ports:
      - ':'
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer:4
    ports:
      - "8090:8080"

volumes:
  db-data:

