services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-appuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-apppass}
      - POSTGRES_DB=${POSTGRES_DB:-appdb}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser}"]
      interval: 5s
      retries: 5

    api:
    build: .
    environment:
      - PGHOST=db
      - PGUSER=${POSTGRES_USER:-appuser}
      - PGPASSWORD=${POSTGRES_PASSWORD:-apppass}
      - PGDATABASE=${POSTGRES_DB:-appdb}
      - PGPORT=5432
      - PORT=${API_PORT:-3000}
    ports:
      - "${HOST_API_PORT:-8082}:${API_PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    ports:
      - "8090:8080"

volumes:
  db-data:

