{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tasktracker-postgres
spec:
  selector:
    app: tasktracker-postgres
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
