apiVersion: v1
kind: Secret
metadata:
  name: tasktracker-postgres
type: Opaque
stringData:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
  database: {{ .Values.postgres.database }}
