apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasktracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasktracker-api
  template:
    metadata:
      labels:
        app: tasktracker-api
    spec:
      containers:
        - name: api
          image: YOURUSER/tasktracker:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: "postgres"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: tasktracker-secrets
                  key: pguser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: tasktracker-secrets
                  key: pgpassword
            - name: PGDATABASE
              value: "appdb"
            - name: PGPORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: tasktracker-api
spec:
  selector:
    app: tasktracker-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
